### ISSUE TITLE
Create ROS Node with specific topics

### ISSUE THREAD

**Issue by JoaoAMarinho** [fs-feup/autonomous-systems#1]
## Tasks

- [X] Create the ROS Node
- [X] ROS Topic (receive path planning path)
- [X] Integrate existing code
- [x] Solve integration problems
