### ISSUE TITLE
Create Path Planning mock topic

### ISSUE THREAD

**Issue by JoaoAMarinho** [fs-feup/autonomous-systems#2]
## Tasks

- [X] Create a mock topic
- [x] Create custom interfaces package for most topics
- [x] Create specific path planning mock interface
